server:
  port: 5050
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: payment
          uri: http://localhost:8001/payment/
          predicates:
            - Path= /payment/**
            #==========================
        - id: stock
          uri: http://localhost:9112/stock/
          predicates:
            - Path= /stock/**
            #==========================

        - id: basket
          uri: http://localhost:9120/basket/
          predicates:
            - Path= /basket/**
            #==========================
        - id: authmarket
          uri: http://localhost:9061/authmarket/
          predicates:
            - Path= /authmarket/**
            #==========================

        - id: transfer
          uri: http://localhost:9116/transfer/
          predicates:
            - Path= /transfer/**
            #==========================

        - id: help
          uri: http://localhost:9117/help/
          predicates:
            - Path= /help/**
            #==========================

        - id: interaction
          uri: http://localhost:9115/interaction/
          predicates:
            - Path= /interaction/**
            #==========================

  application:
    name: gateway


management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway
