server:
  port: 5050
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: payment
          uri: http://localhost:7090/payment/
          predicates:
            - Path= /payment/**
            #==========================
        - id: stok
          uri: http://localhost:7030/stok/
          predicates:
            - Path= /stok/**
            #==========================

        - id: basket
          uri: http://localhost:7050/basket/
          predicates:
            - Path= /basket/**
            #==========================
        - id: auth
          uri: http://localhost:7070/auth/
          predicates:
            - Path= /auth/**
            #==========================

        - id: transfer
          uri: http://localhost:6060/transfer/
          predicates:
            - Path= /transfer/**
            #==========================

        - id: help
          uri: http://localhost:7080/help/
          predicates:
            - Path= /help/**
            #==========================

        - id: interaction
          uri: http://localhost:7020/interaction/
          predicates:
            - Path= /interaction/**
            #==========================

  application:
    name: gateway


management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway
