server:
  port: 5050

eureka:
  client:
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: stok

  redis:
    host: localhost
    port: 6379
    password: 1200
    timeout: 30000
    lettuce:
      pool:
        max-active: 50
        max-idle: 5
        min-idle: 2
        max-wait: 3000